### ISSUE TITLE
My hand hurts!

### ISSUE THREAD

**Issue by KamilT1213** [rm20killer/Quantum#14]
Id recommend a sort of buttons remapping available, the grappling hook in my opinion is the most powerful tool in the game but having to stretch my hand in weird ways to press it is uncomfortable, id recommend adding some sort of input botton change available in the settings or simply rebind it to right mouse click as its also an ability tied to the camera and that button is not used for anything else in the game.

**Comment by rm20killer** [comment]
Added support to use right-click to use the grapple.
